project:
  type: website
  output-dir: build
  resources:
    - "eda/**"

lang: en
language:
  section-title-appendices: "Appendix"

website:
  title: "Interactive Race Analysis Dashboard"
  search: true
  sidebar:
    style: "floating"
    search: true
    contents:
      - index.qmd
      - project_charta.qmd
      - data_report.qmd
      - text: "Streamlit App"
        href: "https://ds24t-3.streamlit.app"
        target: "_blank"
      - presentation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
      

number-sections: true

bibliography: refs.bib
csl: vancouver-brackets.csl

jupyter: python3

execute:
  freeze: auto

editor:
  render-on-save: true